from .domain import Invoice


def demo_invoices() -> list[Invoice]:
    return [
        Invoice(
            id="inv_1001",
            vendor="LumaStack Cloud",
            invoice_number="LUMA-2608-04",
            amount_cents=12_800,
            currency="USD",
            received_at="2026-08-26T08:14:00Z",
            po_number="PO-2148",
            description="Workspace hosting · 12 seats",
            due_date="2026-09-08",
            category="Software",
        ),
        Invoice(
            id="inv_1002",
            vendor="Northstar Courier",
            invoice_number="NS-9041",
            amount_cents=74_200,
            currency="USD",
            received_at="2026-08-26T08:31:00Z",
            po_number="PO-2152",
            description="Same-day delivery · 18 packages",
            due_date="2026-09-04",
            category="Operations",
        ),
        Invoice(
            id="inv_1003",
            vendor="Field & Finch",
            invoice_number="FF-1872",
            amount_cents=28_400,
            currency="USD",
            received_at="2026-08-26T08:43:00Z",
            po_number=None,
            description="Customer research dinner · 6 guests",
            due_date="2026-09-10",
            category="People & culture",
        ),
        Invoice(
            id="inv_1004",
            vendor="Cedar & Co",
            invoice_number="CED-4490",
            amount_cents=19_600,
            currency="USD",
            received_at="2026-08-26T09:05:00Z",
            po_number=None,
            description="Office plants and monthly care",
            due_date="2026-09-05",
            category="Workplace",
        ),
        Invoice(
            id="inv_1005",
            vendor="Atlas Design",
            invoice_number="ATL-8123",
            amount_cents=31_000,
            currency="USD",
            received_at="2026-08-26T09:18:00Z",
            po_number="PO-2155",
            description="Brand system sprint · phase 2",
            due_date="2026-09-12",
            category="Creative",
        ),
        Invoice(
            id="inv_1006",
            vendor="Parcel Hive",
            invoice_number="PH-0219",
            amount_cents=8_800,
            currency="USD",
            received_at="2026-08-26T09:26:00Z",
            po_number=None,
            description="Shipping labels · August batch",
            due_date="2026-09-02",
            category="Operations",
        ),
        Invoice(
            id="inv_1007",
            vendor="LumaStack Cloud",
            invoice_number="LUMA-2608-04",
            amount_cents=12_800,
            currency="USD",
            received_at="2026-08-26T09:44:00Z",
            po_number="PO-2148",
            description="Resubmitted workspace hosting invoice",
            due_date="2026-09-08",
            category="Software",
            duplicate_of="inv_1001",
        ),
        Invoice(
            id="inv_1008",
            vendor="Morrow Studio",
            invoice_number="MOR-3007",
            amount_cents=21_100,
            currency="USD",
            received_at="2026-08-26T10:02:00Z",
            po_number=None,
            description="Product photography · 14 final assets",
            due_date="2026-09-14",
            category="Creative",
        ),
    ]

